### ISSUE TITLE
Components get displayed on translated pages even if they don't have a translated version

### ISSUE THREAD

**Issue by robertpateii** [kamsar/Synthesis#18]
Here's an example image:
https://dl.dropboxusercontent.com/u/6237857/blanks-on-translated-site.png

I was able to fix a similar issue by forcing Versions.Count > 0 in Synthesis's GetChildren(), but that doesn't help with the components being loaded on the page.

Even so, that seems like a work around for a Sitecore bug. Why is Sitecore's GetChildren() returning items that don't exist in the page's language?

**Comment by robertpateii** [comment]
Fixed the issue with components by tweaking Blade. 
See https://github.com/robertpateii/Blade/commit/a237cfb4fdd16f31f2e3b6df0fb5200082711d89

Not sure if that's the best place to fix it. What do you advise?

**Comment by robertpateii** [comment]
My change causes a problem in an edge case where the datasource is an item that has no translations, but has children which do. it will still be returned as null.

Could revert this change, but then I'd need to go into the code of every control and make sure it doesn't appear if its missing its desired content.

**Comment by kamsar** [comment]
Because Shared fields exist independently of language, you can get a 'shell' item with only shared field values for any language, even when a version does not exist in that language containing language-specific fields. It's a bit wacky, but Sitecore does not consider it a bug (I reported it a long time ago and that was the answer I got)

For the stack you're running on I think you've probably changed the right place. For the latest versions, I think it might make sense to have automatically when resolving a viewrendering and as an option on `As<>()` and `AsStronglyTypedCollectionOf<>()`

What was the situation where you had a datasource without a language version and needed the children? Seems pretty edge to me.

**Comment by kamsar** [comment]
Previous implementation notes for future reference:
* Add property for hasversion
* Option on by default to require a version for model resolution
* Param on by default for getchildren etc to require a valid version

**Comment by kamsar** [comment]
This behavior is the default API behavior in Sitecore 8.1. No longer needs additional support.
