### ISSUE TITLE
Rendering Parameters Helper?

### ISSUE THREAD

**Issue by fuzzyducky** [kamsar/Synthesis#46]
I am trying to figure out how to get at rendering parameters. Does something like a GetRenderingParameters method exist, or is there a recommended way to do this?

**Comment by kamsar** [comment]
Because rendering parameters are not actual Sitecore items (internally they map to a query string) their parsing is completely different than a normal item and normal mapping/wrapping doesn't work.

Synthesis does not currently have a mapping path to resolve rendering parameters. I've found that most of the time things that are rendering parameters may well behave just as well if added to the datasource template (there are exceptions, of course). Using datasource template fields also has the advantage that they are workflowed, versioned, and support languages. Whereas rendering parameters do not, unless attached to final renderings which brings its own can of worms.

**Comment by fuzzyducky** [comment]
I'm new to all this, so bear with me. I am noticing that I need to exclude any templates that ultimately inherit from /System/Layout/Rendering Parameters/Standard Rendering Parameters since it ends up inheriting itself in the rendered model. This is because of the reason you state? "Synthesis does not currently have a mapping path to resolve rendering parameters"

**Comment by kamsar** [comment]
It should have no problem with templates, only that it cannot strongly type
rendering parameters for you.

**Comment by fuzzyducky** [comment]
Ah - the issue was that the Standard Rendering Parameters was inheriting itself in sitecore...
